### ISSUE TITLE
DeviceSensorsList PNG

### ISSUE THREAD

**Issue by ZeeshanHKhan** [zkhan1/DeviceSensorsList-Android-app#2]
![sensorslist1](https://user-images.githubusercontent.com/12658606/86034814-e7350780-ba00-11ea-8b46-da52465f2926.png)

![DeviceSensorsList_app](https://user-images.githubusercontent.com/12658606/86034717-c1a7fe00-ba00-11ea-9a6b-2ac13aefe2b6.png)

**Comment by zkhan1** [comment]
![](https://user-images.githubusercontent.com/12658606/85987822-cb574480-b9b3-11ea-9660-f3696156dfb4.png)
